### ISSUE TITLE
results fluctuate

### ISSUE THREAD

**Issue by YounZh** [limuloo/PyDIff#15]
When I train your model on other datasets (such as SID), the validation results fluctuate a lot. Is this normal? Do you have any suggestions for parameter settings? This is my training log, looking forward to your reply.
[train.log](https://github.com/limuloo/PyDIff/files/13784512/train.log)

**Comment by allswin** [comment]
I observed that the validation results in your log become relatively stable after 265k (i.e., Tune-PSNR is around 23.7, and Tune-SSIM is around 0.675). This may be because the diffusion model produces stochastic results. For example, when you change a random number seed, PSNR and SSIM will also bring great changes.

**Comment by limuloo** [comment]
I observed that the validation results in your log become relatively stable after 265k (i.e., Tune-PSNR is around 23.7, and Tune-SSIM is around 0.675). This may be because the diffusion model produces stochastic results. For example, when you change a random number seed, PSNR and SSIM will also bring great changes.

**Comment by YounZh** [comment]
Got it, thank you for your prompt reply and your excellent work.
